Add Coinbase, Gemini and Twitter to known U2F apps.
keepkey/keepkey-firmware pull request #272
Opened 2021-05-02 11:04 UTC by greatwolf

2021-06-02 10:07 UTC, FeliciaAKelley requested changes
Disabled javascript

2021-06-02 10:38 UTC, greatwolf commented
What's the change about? I can't seem to find a difference after clicking `View changes` button.

2022-05-28 15:37 UTC, markrypt0 approved these changes

2022-05-28 15:45 UTC, merged

2022-05-28 15:45 UTC, markrypt0 commented
Merged.